// swift-tools-version: 5.9.0
// AUTO-GENERATED by swift-binify - Prebuilt binary package
import PackageDescription

let package = Package(
    name: "Kingfisher",
    platforms: [.iOS(.v13), .macOS(.v10_15), .tvOS(.v13), .visionOS(.v1), .watchOS(.v6)],
    products: [
        .library(name: "Kingfisher", targets: ["Kingfisher"])
    ],
    targets: [
        .binaryTarget(
            name: "Kingfisher",
            url: "https://github.com/swift-bins/onevcat_Kingfisher/releases/download/8.6.2/Kingfisher.xcframework.zip",
            checksum: "3c928d0e6231dd94190b8e0cdaf82b7895d014111bb3204b9dd82b6856778c17"
        )
    ]
)
